
//      MIT License

//      Copyright (c) 2026 Abhiram Thatikonda

//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:

//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.

//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

//  The cstring library is very much similar to the std::basic_string in C++. 
//  You can refer https://en.cppreference.com/w/cpp/string/basic_string.html

/*
 * Portions of this code are adapted from:
 *   c-string by Steffen Illhardt
 *   https://github.com/german-one/c-string
 *
 * Used under MIT License.
 */

/*
 *  some portions of library are generated by AI.
 *  Just cmake, some comments and a few tests.
 */

/*
 *  Notes:
 * - All operations are byte-based (ASCII/single-byte characters only).
 * - Multibyte encodings (UTF-8, UTF-16, etc.) are not supported.
 * - The cstring support literals as const char[].
 * - Can use any external functions on cstring that doesn't modify the char buffer.
 * - Any function that modifies the char buffer expects `cstring*` as its first parameter and 
 *   any function that doesn't, expects const_cstring as its first parameter.
 * - Parameter which isn't a first param also expects const version of the specific type.
 * - Return values are optional in most cases, except for:
 *     - cstr_init
 *     - cstr_substr
 *   These should be captured.
 */


#ifndef CSTRING_H_LIB_
#define CSTRING_H_LIB_

#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<stdbool.h>


#if defined(__clang__) || defined(__GNUC__)
#define CSTR_NODISCARD                                              __attribute__((warn_unused_result))
#define __cstr__unused		                                        __attribute__((unused))
#define __cstr__always_inline		                                __attribute__((__always_inline__))

#elif defined(_MSC_VER)
#define CSTR_NODISCARD                                              _Check_return_
#define __cstr__always_inline		                                __forceinline
#define __cstr__unused

#else
#define CSTR_NODISCARD
#define __cstr__always_inline
#define __cstr__unused

#endif



#ifndef __has_builtin
#define __has_builtin(x)                                            0
#endif

#if		__has_builtin(__builtin_constant_p) || defined(__GNUC__)
#define pvt_builtin_constant_p(x)	                                __builtin_constant_p(x)
#else
#define pvt_builtin_constant_p(x)	                                0
#endif


// Types:

#define basic_cstring_type			    char*
#define basic_const_cstring			    const char*


typedef basic_cstring_type				cstring;
typedef basic_const_cstring				const_cstring;
typedef struct { cstring it; }			cstr_iterator;
typedef struct { const_cstring it; }	cstr_const_iterator;
typedef struct { cstring it; }			cstr_reverse_iterator;
typedef struct { const_cstring it; }	cstr_const_reverse_iterator;

#define const_iter(iter)                (cstr_const_iterator){ .it = (iter).it }
#define const_reverse_iter(iter)        (cstr_const_reverse_iterator){ .it = (iter).it }

#ifdef CSTRMAX
#undef CSTRMAX
#endif
#ifdef CSTRMIN
#undef CSTRMIN
#endif

#define CSTRMAX(_A__01_, _B__01_)       ((_A__01_) > (_B__01_) ? (_A__01_) : (_B__01_))
#define CSTRMIN(_A__01_, _B__01_)       ((_A__01_) < (_B__01_) ? (_A__01_) : (_B__01_))

#define CSTR_NPOS                       ((size_t)-1)
#define CSTRING_DEFAULT_CAP		        15
#define dummy_func				        (void*)0


/* ----------------------------
        PRIVATE INTERFACE  
   ---------------------------- */

/* functions for allocation and deallocation need to correspond to each other,
   fall back to C library functions if not all are overridden */

#if !defined(pvt_cstr_malloc) || !defined(pvt_cstr_realloc) || \
	!defined(pvt_cstr_free)	  || !defined(pvt_cstr_memcpy) || \
	!defined(pvt_cstr_memmove)

#ifdef pvt_cstr_malloc
#undef pvt_cstr_malloc
#endif
#ifdef pvt_cstr_realloc
#undef pvt_cstr_realloc
#endif
#ifdef pvt_cstr_free
#undef pvt_cstr_free
#endif
#ifdef pvt_cstr_memcpy
#undef pvt_cstr_memcpy
#endif
#ifdef pvt_cstr_strlen
#undef pvt_cstr_strlen
#endif
#ifdef pvt_cstr_memmove
#undef pvt_cstr_memmove
#endif

#define pvt_cstr_malloc			malloc
#define pvt_cstr_realloc		realloc
#define pvt_cstr_free			free
#define pvt_cstr_memcpy		    memcpy
#define pvt_cstr_strlen			strlen
#define pvt_cstr_memmove		memmove
#endif

#ifdef pvt_cstr_assert_enabled
#undef pvt_cstr_assert_enabled
#endif
#ifdef pvt_cstr_assert
#undef pvt_cstr_assert
#endif
#ifdef pvt_cstr_static_assert
#undef pvt_cstr_static_assert
#endif

#define pvt_cstr_assert_enabled 1

#if pvt_cstr_assert_enabled
#define pvt_cstr_assert(cond, fmt)										\
    do{                                                                 \
        if( !(cond) ){                                                  \
            fprintf(stderr, __FILE__ ":%d assertion %s failed: %s\n",   \
                    __LINE__, #cond, fmt);                              \
            exit(1);                                                    \
        }                                                               \
    } while(0)

#define pvt_cstr_static_assert(cond, fmt)			_Static_assert( (cond), fmt );

#else

#define pvt_cstr_assert(cond, str)
#define pvt_cstr_static_assert(cond, str)

#endif



//  metadata for cstring
typedef struct
{
    size_t size;
    size_t capacity;
    bool   is_malloced;
} pvt_cstr_metadata_t;



#define pvt_dat_to_mdata_(ptr)											\
    (((pvt_cstr_metadata_t *)(ptr)) - 1)

#define pvt_dat_to_const_mdata_(ptr)									\
    (((const pvt_cstr_metadata_t *)(ptr)) - 1)

#define pvt_total_cap_(ptr)												\
     ((ptr) ? pvt_dat_to_const_mdata_(ptr)->capacity : 0)

#define pvt_total_size_(ptr)										    \
      ((ptr) ? pvt_dat_to_const_mdata_(ptr)->size : 0)

#define pvt_is_malloced_(ptr)											\
      ((ptr) ? pvt_dat_to_const_mdata_(ptr)->is_malloced : false)


#define pvt_set_total_cap_(ptr, cap)                                    \
    do {                                                                \
        pvt_cstr_assert(ptr, "The cstring instance is null.");			\
        pvt_dat_to_mdata_(ptr)->capacity = (cap);						\
    } while(0)

#define pvt_set_total_size_(ptr, count)                                 \
    do {                                                                \
        pvt_cstr_assert(ptr, "The cstring instance is null.");			\
        pvt_dat_to_mdata_(ptr)->size = (count);                         \
    } while(0)

#define pvt_set_buf_malloced_(ptr, boolean)                             \
    do{                                                                 \
        pvt_cstr_assert(ptr, "The cstring instance is null.");			\
        pvt_dat_to_mdata_(ptr)->is_malloced = (boolean);                \
    } while(0)


#define pvt_copy_(str, other, count)                                            \
    do {                                                                        \
        if(!(str) || !(other)) break;                                           \
        pvt_cstr_memcpy((str), (other), (size_t)(count) * sizeof(*(other)));	\
        (str)[(size_t)(count)] = 0;                                             \
        pvt_set_total_size_(str, count);                                        \
    } while(0)

#define pvt_fill_(str, idx, cnt, ch)                    \
    do {                                                \
        if ((cnt) > 0)                                  \
            memset((str) + (idx), (ch), (cnt));         \
    } while(0)

#define pvt_fill_it_(first, last, cnt, ch)              \
    do{                                                 \
        for(size_t i = 0;                               \
            i < (cnt) && ((first) + i) < (last);        \
            ++i)                                        \
            (first)[i] = (ch);                          \
    } while(0)

/**
 *  Generic Helpers
 * ----------------
 */
#define PVT_GENERIC_SIZE_TYPES( arg_01 )                \
	short     : arg_01, unsigned short     : arg_01,    \
    int       : arg_01, unsigned int       : arg_01,    \
    long      : arg_01, unsigned long      : arg_01,    \
    long long : arg_01, unsigned long long : arg_01

#define PVT_GENERIC_CHAR_TYPES( arg_01 )				\
	char	  : arg_01,	const char		   : arg_01,    \
    int       : arg_01

#define PVT_GENERIC_STRING_TYPES( arg_01 )              \
    cstring						           : arg_01,	\
	const_cstring				           : arg_01 

#define PVT_GENERIC_NORMAL_ITER( arg_01 )               \
    cstr_iterator				           : arg_01,	\
    cstr_const_iterator			           : arg_01

#define PVT_GENERIC_REVERSE_ITER( arg_01 )              \
    cstr_reverse_iterator		           : arg_01,	\
    cstr_const_reverse_iterator            : arg_01

#define PVT_GENERIC_ITER_TYPES( arg_01 )                \
    PVT_GENERIC_NORMAL_ITER(arg_01),                    \
    PVT_GENERIC_REVERSE_ITER(arg_01)

#define PVT_MUTABLE_CSTRING( str )						\
    ( _Generic((str), cstring : 1, default : 0 ) &&		\
	        !pvt_builtin_constant_p(str) )

#define PVT_IS_STRING( str )                            \
    ( _Generic((str),									\
			PVT_GENERIC_STRING_TYPES(1),				\
			default : 0))

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 *      MEMBER FUNCTIONS
 * ---------------------
 */

/*
 * Creates a constant cstring with embedded metadata.
 *
 * Usage:
 *     cstr_literal(str, "Hello world");
 * 
 * Use it like a const char* say,
 *     printf("%s\n", str);
 *     size_t len = cstr_length(str);
 *
 * Notes:
 * - Do NOT modify the returned string (read-only)
 * - Do NOT free it with cstr_free (it is not heap allocated)
 * - Safe to pass anywhere a const char* is expected
 */
#define cstr_literal(name, lit)                                                         \
    const struct {                                                                      \
        pvt_cstr_metadata_t mdata_;                                                     \
        const char data[((sizeof(lit) + sizeof(size_t) - 1) / sizeof(size_t))           \
                                        * sizeof(size_t)];                              \
    } _cstring_literal_container_##name = {{(sizeof(lit) - 1),                          \
                                        (sizeof(lit) - 1), false}, lit};                \
    const_cstring name = _cstring_literal_container_##name.data


/* Generic constructor for cstring.
 *
 * Use like:
 *   cstr_init(str)                          -> default init
 *   cstr_init(str, size | "text")           -> size or copy init
 *   cstr_init(str, n, ch | first, last)     -> fill or range init
 *   cstr_init(str, other, start, offset)    -> substring init
 * 
 *  returns `cstring`
 */
#define cstr_init(...) \
    __cstr_init_chooser(__VA_ARGS__)(__VA_ARGS__)


/**
 *  Free all memory associated with the cstring and set it
 *  to NULL.
 */
static inline void
cstr_free(cstring *ptr)
{
    if(*ptr && pvt_is_malloced_(*ptr)){
        pvt_cstr_free(pvt_dat_to_mdata_(*ptr));
    }
    (*ptr) = NULL;
}


/**
 *      SIZE & CAPACITY 
 *  -------------------
 */

/**
 * returns the total size of the cstring as size_t
 */
__cstr__always_inline
static inline size_t __cstr__unused
cstr_size(const_cstring str)
{
    return pvt_total_size_(str);
}

/**
 * returns the total length of the cstring as size_t
 */
__cstr__always_inline
static inline size_t __cstr__unused
cstr_length(const_cstring str)
{
    return pvt_total_size_(str);
}

/**
 * returns the total capacity of the cstring as size_t
 */
__cstr__always_inline
static inline size_t __cstr__unused
cstr_capacity(const_cstring str)
{
    return pvt_total_cap_(str);
}

/**
 * returns the maximum number of elements the cstring is able 
 * to hold due to system or library implementation limitations.
 */
__cstr__always_inline
static inline size_t __cstr__unused
cstr_max_size()
{
	return ((size_t)-1) - sizeof(pvt_cstr_metadata_t) - 1;
}

/**
 * requests the removal of unused capacity. It is a request 
 * to reduce capacity() to size().
 */
void __cstr__unused
cstr_shrink_to_fit(cstring *str);

/**
 * requests that the cstring capacity be adapted to a planned 
 * change of up to new_cap characters.
 */
void __cstr__unused
cstr_reserve(cstring *str, size_t new_cap);

/**
 * requests the number of increments needed to go from first to last.
 */
#define cstr_distance( first, last )						    \
	(size_t)_Generic((first),								    \
			PVT_GENERIC_NORMAL_ITER((last).it - (first).it),    \
            PVT_GENERIC_REVERSE_ITER((first).it - (last).it)    \
		)

/*
 *   Input and Output 
 * ------------------
 */

/**
 * read the string buffer from the stream
 */
void __cstr__unused
cstr_getstr(cstring *str, size_t cnt, FILE* stream);

/**
 * print cstring to the stdout with a neswline at the end.
 */
void __cstr__unused
cstr_println(const_cstring str);


/*
 *  Element access
 * ---------------
 */

/**
 * return the character at position `pos` in the cstring,
 * else -1 is returned.
 */
__cstr__always_inline
static inline char __cstr__unused
cstr_at(const_cstring str, size_t pos)
{
    return (cstr_size(str)        &&
            pos < cstr_max_size() &&
            pos < cstr_size(str)) 
            ? str[pos] : -1;
}

/**
 * return the first character in the cstring, else -1 is returned.
 */
__cstr__always_inline
static inline char __cstr__unused
cstr_front(const_cstring str)
{
    return (cstr_size(str) &&
            cstr_size(str) < cstr_max_size()) 
            ? str[0] : -1;
}

/**
 * return the last character in the cstring, else -1 is returned.
 */
__cstr__always_inline
static inline char __cstr__unused
cstr_back(const_cstring str)
{
    size_t size = cstr_size(str);
    return (size && size < cstr_max_size()) ? str[size - 1] : -1;
}

/**
 * return true/1 if NULL or empty, false/0 if non-empty.
 */
__cstr__always_inline
static inline bool __cstr__unused
cstr_empty(const_cstring str)
{
    return (cstr_size(str) == (size_t)0);
}


/*
 *  Iterators
 * ----------
 */

/**
 * returns a mutable iterator to the first character of the cstring.
 */
__cstr__always_inline
static inline cstr_iterator __cstr__unused
cstr_begin(cstring str)
{
    return (cstr_iterator){ str };
}

/**
 * returns a constant iterator to the first character of the cstring.
 */
__cstr__always_inline
static inline cstr_const_iterator __cstr__unused
cstr_cbegin(const_cstring str)
{
    return (cstr_const_iterator){ str };
}

/**
 * returns a mutable iterator to the character following the last 
 * character of the string. This character acts as a placeholder, 
 * attempting to access it results in undefined behavior. 
 */
__cstr__always_inline
static inline cstr_iterator __cstr__unused
cstr_end(cstring str)
{
    return (cstr_iterator){ (str + cstr_size(str)) };
}

/**
 * returns a constant iterator to the character following the last
 * character of the string. This character acts as a placeholder,
 * attempting to access it results in undefined behavior.
 */
__cstr__always_inline
static inline cstr_const_iterator __cstr__unused
cstr_cend(const_cstring str)
{
    return (cstr_const_iterator){ (str + cstr_size(str)) };
}

/**
 * returns a mutable reverse iterator to the first character of the
 * reversed cstring. It corresponds to the last character of the
 * non-reversed cstring.
 */
__cstr__always_inline
static inline cstr_reverse_iterator __cstr__unused
cstr_rbegin(cstring str)
{
    return (cstr_reverse_iterator){ (str + cstr_size(str) - 1) };
}

/**
 * returns a constant reverse iterator to the first character of the
 * reversed cstring. It corresponds to the last character of the
 * non-reversed cstring.
 */
__cstr__always_inline
static inline cstr_const_reverse_iterator __cstr__unused
cstr_crbegin(const_cstring str)
{
    return (cstr_const_reverse_iterator){ (str + cstr_size(str) - 1) };
}

/**
 * returns a mutable reverse iterator to the character following the last
 * character of the reversed cstring. It corresponds to the character
 * preceding the first character of the non-reversed cstring.This character
 * acts as a placeholder, attempting to access it results in undefined behavior.
 */
__cstr__always_inline
static inline cstr_reverse_iterator __cstr__unused
cstr_rend(cstring str)
{
    return (cstr_reverse_iterator){ (str - 1) };
}

/**
 * returns a constant reverse iterator to the character following the last
 * character of the reversed cstring. It corresponds to the character
 * preceding the first character of the non-reversed cstring. This character
 * acts as a placeholder, attempting to access it results in undefined behavior.
 */
__cstr__always_inline
static inline cstr_const_reverse_iterator __cstr__unused
cstr_crend(const_cstring str)
{
    return (cstr_const_reverse_iterator){ (str - 1) };
}

/**
 * move the iterator to the next element.
 */
#define iter_next(it)                                   \
    _Generic((it),                                      \
        cstr_iterator*: intl_iter_next,                 \
        cstr_const_iterator*: intl_citer_next,          \
        cstr_reverse_iterator*: intl_riter_next,        \
        cstr_const_reverse_iterator*: intl_criter_next  \
    )(it)

/**
 * move the iterator to the previous element.
 */
#define iter_prev(it)                                   \
    _Generic((it),                                      \
        cstr_iterator*: intl_iter_prev,                 \
        cstr_const_iterator*: intl_citer_prev,          \
        cstr_reverse_iterator*: intl_riter_prev,        \
        cstr_const_reverse_iterator*: intl_criter_prev  \
    )(it)


/*
 *  Modifiers
 * ----------
 */


/* 
 * Generic insert function for cstring.
 *
 * Usage:
 *   cstr_insert(str, index, ch | "text")               -> insert char or string
 *   cstr_insert(str, index, count, ch | "text")        -> insert repeated char or string
 *   cstr_insert(str, index, other, pos, count)         -> insert substring
 * 
 *  returns `cstring` or `cstr_iterator`
 */
#define cstr_insert(...) \
    __cstr_insert_chooser(__VA_ARGS__)(__VA_ARGS__)

/* 
 * Generic erase function for cstring.
 *
 * Usage:
 *   cstr_erase(str, index, count)                      -> erase by index
 *   cstr_erase(str, pos)                               -> erase single element (iterator)
 *   cstr_erase(str, first, last)                       -> erase range
 *  
 *  returns `cstring` or `cstr_iterator`
 */
#define cstr_erase(...) \
    __cstr_erase_chooser(__VA_ARGS__)(__VA_ARGS__)

/*
 * Generic assign function for cstring.
 *
 * Usage:
 *   cstr_assign(str, other);                           -> assign entire string
 *   cstr_assign(str, other, count);                    -> assign first 'count' characters
 *   cstr_assign(str, other, pos, count);               -> assign substring [pos, pos+count)
 *   cstr_assign(str, count, ch);                       -> assign 'count' copies of character 'ch'
 *  
 *  returns `cstring`
 */
#define cstr_assign(...) \
    __cstr_assign_chooser(__VA_ARGS__)(__VA_ARGS__)

/*
 * Generic append function for cstring.
 *
 * Usage:
 *   cstr_append(str, other)                            → append full string
 *   cstr_append(str, other, count)                     → append first `count` chars of string
 *   cstr_append(str, count, ch)                        → append `count` copies of character `ch`
 *   cstr_append(str, other, pos, count);               → append substring [pos, pos+count)
 *
 *   returns `cstring`
 */
#define cstr_append(...) \
    __cstr_append_chooser(__VA_ARGS__)(__VA_ARGS__)


/*
 * Generic replace function for cstring.
 *
 * Usage:
 *   cstr_replace(str, first, last, count2, ch)         → replace [first,last) with count2 copies of ch
 *   cstr_replace(str, first, last, other, count2)      → replace [first,last) with first count2 chars of other
 *   cstr_replace(str, pos, count, count2, ch)          → replace [pos,pos+count) with count2 copies of ch
 *   cstr_replace(str, pos, count, other, pos2, count2) → replace [pos,pos+count) with other[pos2:pos2+count2)
 *   cstr_replace(str, first, last, other)              → replace [first,last) with full string other
 *   cstr_replace(str, pos, count, other, count2)       → replace [pos,pos+count) with first count2 chars of other
 *
 *   - Ranges are half-open: [start, end)
 *  returns `cstring`
 */
#define cstr_replace(...) \
    __cstr_replace_chooser(__VA_ARGS__)(__VA_ARGS__)


/**
 * Removes all characters from the string. All pointers, 
 * references, and iterators are invalidated.
 */
static inline void __cstr__unused
cstr_clear(cstring *str)
{
    pvt_fill_(*str, 0, cstr_size(*str), 0);
    pvt_set_total_size_(*str, 0);
}

/*
 * Appends the given character ch to the end of the cstring.
 */
void __cstr__unused
cstr_push_back(cstring *str, const char ch);

/*
 * Removes the last character from the cstring.
 */
void __cstr__unused
cstr_pop_back(cstring *str);

/*
 * Copies a substring other[pos, pos + count) to cstring pointed to by str.
 * The resulting character string is not null-terminated.
 */
size_t __cstr__unused 
cstr_copy(cstring *str, const_cstring other, const size_t count,
          const size_t pos);

/**
 * Resizes the cstring to contain count characters.
 * If the current size is less than count, additional characters are appended.
 * Pass 0 at `ch` as default.
 */
void __cstr__unused
cstr_resize(cstring *str, const size_t count, const char ch);

/**
 * Exchanges the contents of the string with those of other.
 * All iterators and references may be invalidated.
 */
void __cstr__unused
cstr_swap(cstring *str, cstring *other);
 

/*
 *  Operations
 * -----------
 */

/**
 * Returns a substring of range [pos, pos + count) or [pos, size()). 
 */
CSTR_NODISCARD
cstring __cstr__unused
cstr_substr(const_cstring str, const size_t pos, const size_t count);

/**
 * Generic compare function for cstring.
 *
 * Usage:
 *   cstr_compare(str, other)                               -> compare str with other
 *   cstr_compare(str, pos1, count1, other)                 -> compare str[pos1, pos1+count1) with other
 *   cstr_compare(str, count1, other, count2)               -> compare count1 of str with count2 of other
 *   cstr_compare(str, pos1, count1, other, pos2)           -> compare str[pos1, pos1+count1) with other+pos2
 *   cstr_compare(str, pos1, count1, other, pos2, count2)   -> compare str[pos1, pos1+count1) with other[pos2, pos2+count2)
 *
 *   - Ranges are half-open: [start, end)
 *  returns `int`
 */
#define cstr_compare(...) \
    __cstr_compare_chooser(__VA_ARGS__)(__VA_ARGS__)

/**
 *  Generic replace function for cstring.
 * 
 *  cstr_find(str, ch)                  -> find first character ch in str
 *  cstr_find(str, other)               -> find first substring equal to other in str
 *  cstr_find(str, ch, pos)             -> find first character ch in (str + pos)
 *  cstr_find(str, other, pos)          -> find first substring equal to other in (str + pos)
 *  cstr_find(str, other, pos, count)   -> find first substring equal to other in str[pos, pos+count)
 *  
 *  returns `size_t`
 */
#define cstr_find(...) \
    __cstr_find_chooser(__VA_ARGS__)(__VA_ARGS__)

/**
 *  Generic contains function for cstring.
 * 
 *  cstr_contains(str, ch)              -> Check if the cstring contains the character ch
 *  cstr_contains(str, other)           -> Check if the cstring contains the substring other
 *  
 *  returns `bool`
 */
#define cstr_contains(...) \
    __cstr_contains_chooser(__VA_ARGS__)(__VA_ARGS__)

/**
 *  Generic starts_with function for cstring.
 * 
 *  cstr_starts_with(str, ch)              -> Check if the cstring starts with the character ch
 *  cstr_starts_with(str, other)           -> Check if the cstring starts with the prefix other
 *  
 *  returns `bool`
 */
#define cstr_starts_with(...) \
    __cstr_starts_with_chooser(__VA_ARGS__)(__VA_ARGS__)

/**
 *  Generic ends_with function for cstring.
 * 
 *  cstr_ends_with(str, ch)              -> Check if the cstring ends with the character ch
 *  cstr_ends_with(str, other)           -> Check if the cstring ends with the suffix other
 *  
 *  returns `bool`
 */
#define cstr_ends_with(...) \
    __cstr_ends_with_chooser(__VA_ARGS__)(__VA_ARGS__)



// ============================================================================
// INTERNAL MACROS (DO NOT USE)
// ============================================================================



/*      CONSTRUCTOR
 * ----------------
 */
#define __cstr_init_get_macro(_0,_1,_2,_3,NAME,...) NAME

#define __cstr_init_chooser(...)            \
    __cstr_init_get_macro(, ##__VA_ARGS__,  \
        __cstr_init_3,                      \
        __cstr_init_2,                      \
        __cstr_init_1,                      \
        __cstr_init_0)

#define __cstr_init_0()                                 \
    intl_default_constructor()

#define __cstr_init_1(a)                                \
    _Generic((a),                                       \
        PVT_GENERIC_SIZE_TYPES(intl_init_w_size),       \
        PVT_GENERIC_STRING_TYPES(intl_copy_constructor) \
    )(a)

#define __cstr_init_2(a, b)                             \
    _Generic((a),                                       \
        PVT_GENERIC_SIZE_TYPES(intl_init_cpy_ch),       \
        PVT_GENERIC_ITER_TYPES(intl_init_cpy_str_w_iter)\
    )(a, b)

#define __cstr_init_3(other, start, offset)             \
    intl_init_cpy_str_w_off(other, start, offset)


/*      INSERT
 *------------
 */

#define __cstr_insert_get_macro(_1,_2,_3,_4,_5,NAME,...) NAME

#define __cstr_insert_chooser(...)      \
    __cstr_insert_get_macro(__VA_ARGS__,\
        __cstr_insert_5,                \
        __cstr_insert_4,                \
        __cstr_insert_3)

#define __cstr_insert_3(str, pos, x)                    \
    _Generic((pos),                                     \
        PVT_GENERIC_SIZE_TYPES(_Generic((x),            \
            PVT_GENERIC_STRING_TYPES(intl_insert_str),  \
            default: dummy_func                         \
        )),                                             \
        cstr_iterator : intl_insert_iter_ch,            \
        cstr_const_iterator : intl_insert_citer_ch      \
    )(str, pos, x)

#define __cstr_insert_4(str, pos, a, b)                     \
    _Generic((pos),                                         \
        PVT_GENERIC_SIZE_TYPES(_Generic((b),                \
            PVT_GENERIC_CHAR_TYPES(intl_insert_cnt_ch),     \
            PVT_GENERIC_STRING_TYPES(intl_insert_str_range),\
            default: dummy_func                             \
        )),                                                 \
        cstr_iterator : intl_insert_iter_cnt_ch,            \
        cstr_const_iterator : intl_insert_citer_cnt_ch      \
    )(str, pos, a, b)

#define __cstr_insert_5(str, index, other, pos, count)      \
    intl_insert_substr(str, index, other, pos, count)

/*      ASSIGN
 * -----------
 */

#define __cstr_assign_get_macro(_1,_2,_3,_4,NAME,...) NAME

#define __cstr_assign_chooser(...)      \
    __cstr_assign_get_macro(__VA_ARGS__,\
        __cstr_assign_4,                \
        __cstr_assign_3,                \
        __cstr_assign_2)

#define __cstr_assign_2(str, a)                     \
    _Generic((a),                                   \
        PVT_GENERIC_STRING_TYPES(intl_assign_str)   \
    )(str, a)

#define __cstr_assign_3(str, a, b)                          \
    _Generic((a),                                           \
        PVT_GENERIC_STRING_TYPES(intl_assign_str_offset),   \
        PVT_GENERIC_SIZE_TYPES(intl_assign_cnt_ch)          \
    )(str, a, b)

#define __cstr_assign_4(str, other, pos, count)    \
    intl_assign_str_range(str, other, pos, count)


/*      APPEND
 * -----------
 */
#define __cstr_append_get_macro(_1,_2,_3,_4,NAME,...) NAME

#define __cstr_append_chooser(...)          \
    __cstr_append_get_macro(__VA_ARGS__,    \
        intl_append_substr,                 \
        __cstr_append_3,                    \
        intl_append_str                     \
    )

#define __cstr_append_3(str, a, b)                          \
    _Generic((a),                                           \
        PVT_GENERIC_STRING_TYPES(intl_append_str_offset),   \
        PVT_GENERIC_SIZE_TYPES(intl_append_cnt_ch),         \
        default: dummy_func                                 \
    )(str, a, b)


/*
 *      REPLACE 
 * ------------
 */

#define __cstr_replace_get_macro(_1,_2,_3,_4,_5,_6,NAME,...) NAME

#define __cstr_replace_chooser(...)         \
    __cstr_replace_get_macro(__VA_ARGS__,   \
        intl_replace_substr,                \
        __cstr_replace_5,                   \
        intl_replace_it_str                 \
    )

#define __cstr_replace_5(str, a, b, c, d)                       \
    _Generic((a),                                               \
        PVT_GENERIC_NORMAL_ITER(_Generic((c),                   \
            PVT_GENERIC_SIZE_TYPES(intl_replace_it_fill_ch),    \
            PVT_GENERIC_STRING_TYPES(intl_replace_it_str_off)   \
        )),                                                     \
        PVT_GENERIC_SIZE_TYPES(_Generic((c),                    \
            PVT_GENERIC_STRING_TYPES(intl_replace_str_off),     \
            PVT_GENERIC_SIZE_TYPES(intl_replace_fill_ch)        \
        ))                                                      \
    )(str, a, b, c, d)


/*
 *      ERASE 
 * ----------
 */

#define __cstr_erase_get_macro(_1,_2,_3,NAME,...) NAME

#define __cstr_erase_chooser(...) \
    __cstr_erase_get_macro(__VA_ARGS__, \
        __cstr_erase_3,                 \
        __cstr_erase_2)                 \


#define __cstr_erase_2(str, a)                          \
    _Generic((a),                                       \
        cstr_iterator: intl_erase_ch_iter,              \
        cstr_const_iterator: intl_erase_ch_citer        \
    )(str, a)

#define __cstr_erase_3(str, a, b)                       \
    _Generic((a),                                       \
        PVT_GENERIC_SIZE_TYPES(intl_erase_idx),         \
        cstr_iterator: intl_erase_range_iter,           \
        cstr_const_iterator: intl_erase_range_citer     \
    )(str, a, b)

/*
 *      COMPARE
 * ------------
 */
#define __cstr_compare_get_macro(_1,_2,_3,_4,_5,_6,NAME,...) NAME

#define __cstr_compare_chooser(...)         \
    __cstr_compare_get_macro(__VA_ARGS__,   \
        intl_compare_range_str_range,       \
        intl_compare_range_str_pos,         \
        __cstr_compare_4,                   \
        dummy_func,                         \
        intl_compare_str                    \
    )

#define __cstr_compare_4(str, a, b, c)                          \
    _Generic((b),                                               \
        PVT_GENERIC_STRING_TYPES(intl_compare_offset_str_count),\
        PVT_GENERIC_SIZE_TYPES(intl_compare_range_str)          \
    )(str, a, b, c)

/**
 *      CONTAINS
 * -------------
 */

#define __cstr_contains_chooser(str, other)         \
    _Generic((other),                               \
        PVT_GENERIC_CHAR_TYPES(intl_contains_ch),   \
        PVT_GENERIC_STRING_TYPES(intl_contains_str),\
        default: dummy_func                         \
    )

/**
 *      STARTS_WITH
 * ----------------
 */

#define __cstr_starts_with_chooser(str, other)          \
    _Generic((other),                                   \
        PVT_GENERIC_CHAR_TYPES(intl_starts_with_ch),    \
        PVT_GENERIC_STRING_TYPES(intl_starts_with_str), \
        default: dummy_func                             \
    )

/**
 *      ENDS_WITH
 * --------------
 */

#define __cstr_ends_with_chooser(str, other)            \
    _Generic((other),                                   \
        PVT_GENERIC_CHAR_TYPES(intl_ends_with_ch),      \
        PVT_GENERIC_STRING_TYPES(intl_ends_with_str),   \
        default: dummy_func                             \
    )


/*
 *      FIND
 * ---------
 */
#define __cstr_find_get_macro(_1,_2,_3,_4,NAME,...) NAME

#define __cstr_find_chooser(...)    \
    __cstr_find_get_macro(__VA_ARGS__,  \
        intl_find_str_range,            \
        __cstr_find_3,                  \
        __cstr_find_2)
    

#define __cstr_find_2(str, _2)                      \
    _Generic( (_2),                                 \
        PVT_GENERIC_STRING_TYPES(intl_find_str),    \
        PVT_GENERIC_CHAR_TYPES(intl_find_ch),       \
        default : dummy_func                        \
    )(str, _2)

#define __cstr_find_3(str, _2, pos)                     \
    _Generic( (_2),                                     \
        PVT_GENERIC_STRING_TYPES(intl_find_str_offset), \
        PVT_GENERIC_CHAR_TYPES(intl_find_ch_offset),    \
        default : dummy_func                            \
    )(str, _2, pos)


// ============================================================================
// INTERNAL FUNCTIONS (DO NOT USE)
// ============================================================================


/*
 *  Functions to move the iterators to forward or backward
 *  ------------------------------------------------------
 */

__cstr__always_inline
static inline void __cstr__unused
intl_iter_next(cstr_iterator *it)                   {   it->it++;   }

__cstr__always_inline
static inline void __cstr__unused
intl_citer_next(cstr_const_iterator *it)            {   it->it++;   }

__cstr__always_inline
static inline void __cstr__unused
intl_riter_next(cstr_reverse_iterator *it)          {   it->it--;   }

__cstr__always_inline
static inline void __cstr__unused
intl_criter_next(cstr_const_reverse_iterator *it)   {   it->it--;   }

__cstr__always_inline
static inline void __cstr__unused
intl_iter_prev(cstr_iterator *it)                   {   it->it--;   }

__cstr__always_inline
static inline void __cstr__unused
intl_citer_prev(cstr_const_iterator *it)            {   it->it--;   }

__cstr__always_inline
static inline void __cstr__unused
intl_riter_prev(cstr_reverse_iterator *it)          {   it->it++;   }

__cstr__always_inline
static inline void __cstr__unused
intl_criter_prev(cstr_const_reverse_iterator *it)   {   it->it++;   }


/*
 *	Functions to cstring overloaded Constructor
 *  -------------------------------------------
 */

CSTR_NODISCARD  __attribute__((malloc))
cstring __cstr__unused
intl_init_cpy_ch(const size_t cnt, const char ch);


CSTR_NODISCARD  __attribute__((malloc))
cstring __cstr__unused
intl_copy_constructor(const_cstring other);


CSTR_NODISCARD  __attribute__((malloc))
cstring __cstr__unused
intl_init_cpy_str_w_iter(cstr_iterator begin, 
                    cstr_iterator end);

CSTR_NODISCARD  __attribute__((malloc))
cstring __cstr__unused
intl_init_cpy_str_w_off(const_cstring other,
                    const size_t start, const size_t offset);

CSTR_NODISCARD  __attribute__((malloc))
static inline cstring __cstr__unused
intl_init_w_size(const size_t cnt)
{
    return intl_init_cpy_ch(cnt, ' ');
}

CSTR_NODISCARD  __attribute__((malloc))
static inline cstring __cstr__unused 
intl_default_constructor()
{
    return intl_init_cpy_ch(0, 0);
}

/*
 *  Functions to assign cstring
 *  ---------------------------
 */

cstring __cstr__unused
intl_assign_str_range(cstring *str, const_cstring other,
                    const size_t pos, const size_t count);

cstring __cstr__unused
intl_assign_cnt_ch(cstring *str, const size_t count, const char ch);

static inline cstring __cstr__unused
intl_assign_str_offset(cstring *str, const_cstring other, 
                    const size_t count)
{
    return intl_assign_str_range(str, other, 0, count);
}

static inline cstring __cstr__unused
intl_assign_str(cstring *str, const_cstring other)
{
    return intl_assign_str_range(str, other, 0, pvt_cstr_strlen(other));
}


//****************************
//	        Modifiers
//****************************


/*
 *  Functions to erase characters
 * ------------------------------
 */

cstr_iterator __cstr__unused
intl_erase_range_citer(cstring *str,
                    cstr_const_iterator first,
                    cstr_const_iterator last);

static inline cstr_iterator __cstr__unused
intl_erase_range_iter(cstring *str, cstr_iterator first,
                    cstr_iterator last)
{
    return intl_erase_range_citer(str, const_iter(first), const_iter(last));
}

static inline cstring __cstr__unused
intl_erase_idx(cstring *str, const size_t index,
                    const size_t count)
{
    cstring str_ = *str;
    size_t count_ = CSTRMIN(count + index, cstr_size(str_));

    intl_erase_range_iter(&str_, cstr_begin(str_ + index), 
                    cstr_begin(str_ + count_));
    return str_;
}

static inline cstr_iterator __cstr__unused
intl_erase_ch_iter(cstring *str, cstr_iterator pos)
{
    return intl_erase_range_iter(str, pos,
                    (cstr_iterator){ .it = pos.it + 1 });
}

static inline cstr_iterator __cstr__unused
intl_erase_ch_citer(cstring *str, cstr_const_iterator pos)
{
    return intl_erase_range_citer(str, pos,
                    (cstr_const_iterator){ .it = pos.it + 1 });
}


/*
 *	Functions to insert characters
 * -------------------------------
 */

cstring __cstr__unused
intl_insert_cnt_ch(cstring *str, const size_t index, 
                    const size_t count, const char ch);

cstring __cstr__unused
intl_insert_str_range(cstring *str, const size_t index, 
                    const size_t count, const_cstring other);

static inline cstring __cstr__unused
intl_insert_str(cstring *str, const size_t index, const_cstring other)
{
    return intl_insert_str_range(str, index,
                    pvt_cstr_strlen(other), other);
}

static inline cstring __cstr__unused
intl_insert_substr(cstring *str, const size_t index, 
		           const_cstring other, const size_t pos,
                   const size_t count)
{
	return intl_insert_str(str, index, cstr_substr(other, pos, count));
}



cstr_iterator __cstr__unused
intl_insert_iter_cnt_ch(cstring *str, cstr_iterator pos, 
                    const size_t count, const char ch);

static inline cstr_iterator __cstr__unused
intl_insert_citer_cnt_ch(cstring *str, cstr_const_iterator pos,
                    const size_t count, const char ch)
{
    return intl_insert_iter_cnt_ch(str, 
                    (cstr_iterator){ (cstring)pos.it }, count, ch);
}

static inline cstr_iterator __cstr__unused
intl_insert_iter_ch(cstring *str, cstr_iterator pos, const char ch)
{
    return intl_insert_iter_cnt_ch(str, pos, 1, ch);
}

static inline cstr_iterator __cstr__unused
intl_insert_citer_ch(cstring *str, cstr_const_iterator pos, 
                    const char ch)
{
    return intl_insert_citer_cnt_ch(str, pos, 1, ch);
}


/*
 *	Functions to append characters
 * -------------------------------
 */
static inline cstring __cstr__unused
intl_append_substr(cstring *str, const_cstring other,
                    const size_t pos, const size_t count)
{
    return intl_insert_substr(str, cstr_size(*str), 
                    other, pos, count);
}

static inline cstring __cstr__unused
intl_append_str_offset(cstring *str, const_cstring other,
                    const size_t count)
{
    return intl_append_substr(str, other, 0, count);
}

static inline cstring __cstr__unused
intl_append_str(cstring *str, const_cstring other)
{
    return intl_insert_str(str, cstr_size(*str), other);
}

static inline cstring __cstr__unused
intl_append_cnt_ch(cstring *str, const size_t count, const char ch)
{
    return intl_insert_cnt_ch(str, cstr_size(*str), count, ch);
}


/**
 *  Functions to replace characters
 *  -------------------------------
 */

cstring __cstr__unused
intl_replace_it_fill_ch(cstring *str, cstr_const_iterator first,
                    cstr_const_iterator last, const size_t count2,
                    const char ch);

cstring __cstr__unused
intl_replace_it_str_off(cstring *str, cstr_const_iterator first,
                    cstr_const_iterator last, const_cstring other,
                    const size_t count2);


static inline cstring __cstr__unused
intl_replace_fill_ch(cstring *str, const size_t pos,
                    const size_t count, const size_t count2,
                    const char ch)
{
    return intl_replace_it_fill_ch(str, cstr_cbegin(*str + pos),
                    cstr_cbegin(*str + pos + count), count2 , ch);
}

static inline cstring __cstr__unused
intl_replace_substr(cstring *str, const size_t pos, const size_t count,
                    const_cstring other, const size_t pos2,
                    const size_t count2)
{
    return intl_replace_it_str_off(str, cstr_cbegin(*str + pos),
                    cstr_cbegin(*str + pos + count), &other[pos2], count2);
}


static inline cstring __cstr__unused
intl_replace_it_str(cstring *str, cstr_const_iterator first,
                    cstr_const_iterator last, const_cstring other)
{
    return intl_replace_it_str_off(str, first, last, other,
                    pvt_cstr_strlen(other));
}

static inline cstring __cstr__unused
intl_replace_str_off(cstring *str, const size_t pos, const size_t count,
                    const_cstring other, const size_t count2)
{
    return intl_replace_substr(str, pos, count, other, 0, count2);
}

/**
 *      Functions to compare strings
 * ---------------------------------
 */

int __cstr__unused
intl_compare_range_str_range(const_cstring str, const size_t pos1,
                    const size_t count1, const_cstring other,
                    const size_t pos2, const size_t count2);

static inline int __cstr__unused
intl_compare_str(const_cstring str, const_cstring other)
{
    return intl_compare_range_str_range(str, 0, cstr_size(str),
                    other, 0, pvt_cstr_strlen(other));
}

static inline int __cstr__unused
intl_compare_range_str(const_cstring str, const size_t pos1,
                    const size_t count1, const_cstring other)
{
    return intl_compare_range_str_range(str, pos1, count1,
                    other, 0, pvt_cstr_strlen(other));
}

static inline int __cstr__unused
intl_compare_range_str_pos(const_cstring str, const size_t pos1,
                    const size_t count1, const_cstring other,
                    const size_t pos2)
{
    return intl_compare_range_str_range(str, pos1, count1,
                    other, pos2, pvt_cstr_strlen(other));
}

static inline int __cstr__unused
intl_compare_offset_str_count(const_cstring str, const size_t count1,
                    const_cstring other, const size_t count2)
{
    return intl_compare_range_str_range(str, 0, count1,
                    other, 0, count2);
}

/**
 *  Functions to find first occurrence of an expression
 *  ---------------------------------------------------
 */

size_t __cstr__unused
intl_find_str_range(const_cstring str, const_cstring other,
                    const size_t pos, const size_t count);

size_t __cstr__unused
intl_find_ch_offset(const_cstring str, const char ch, const size_t pos);


static inline size_t __cstr__unused
intl_find_str_offset(const_cstring str, const_cstring other, const size_t pos)
{
    return intl_find_str_range(str, other, pos, cstr_size(str));
}

static inline size_t __cstr__unused
intl_find_str(const_cstring str, const_cstring other)
{
    return intl_find_str_range(str, other, 0, cstr_size(str));
}

static inline size_t __cstr__unused
intl_find_ch(const_cstring str, const char ch)
{
    return intl_find_ch_offset(str, ch, 0);
}

/**
 *  Functions to check for substring(contains)
 */
static inline bool __cstr__unused
intl_contains_ch(const_cstring str, const char ch)
{
    return (intl_find_ch(str, ch) != CSTR_NPOS);
}

static inline bool __cstr__unused
intl_contains_str(const_cstring str, const_cstring other)
{
    return (intl_find_str(str, other) != CSTR_NPOS);
}

/**
 *  Functions to check for a prefix(starts_with)
 */
static inline bool __cstr__unused
intl_starts_with_ch(const_cstring str, const char ch)
{
    return (!cstr_empty(str) && cstr_size(str) && cstr_front(str) == ch);
}

static inline bool __cstr__unused
intl_starts_with_str(const_cstring str, const_cstring other)
{
    size_t count = pvt_cstr_strlen(other);
    return !cstr_empty(str) && count && 
            strncmp(str, other, count) == 0;
}


/**
 *  Functions to check for a suffix(ends_with)
 */
static inline bool __cstr__unused
intl_ends_with_ch(const_cstring str, const char ch)
{
    return (!cstr_empty(str) && cstr_size(str) && cstr_back(str) == ch);
}

static inline bool __cstr__unused
intl_ends_with_str(const_cstring str, const_cstring other)
{
    size_t count = pvt_cstr_strlen(other);
    return !cstr_empty(str) && count && 
            strncmp(str + cstr_size(str) - count, other, count) == 0;   
}
#endif
